# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id       = "paketo-buildpacks/spring-boot"
name     = "Paketo Spring Boot Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/spring-boot"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BP_BOOT_NATIVE_IMAGE"
description = "the build to create a native image (requires GraalVM)"
build       = true

[[metadata.configurations]]
name        = "BP_BOOT_NATIVE_IMAGE_BUILD_ARGUMENTS"
description = "the arguments to pass to the native-image command"
build       = true

[[metadata.dependencies]]
id      = "spring-graalvm-native"
name    = "Spring GraalVM Native Feature"
version = "0.7.1"
uri     = "https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native/0.7.1/spring-graalvm-native-0.7.1.jar"
sha256  = "af5792294734e26620bcd13868a2e6f53c20008c0232dac42669f826efd2d3f2"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/spring-projects-experimental/spring-graal-native/blob/master/LICENSE.txt"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
